export const PERMISSIONS = {
  USER_CREATE: 'USER_CREATE',
  USER_READ: 'USER_READ',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',
  ROLE_MANAGE: 'ROLE_MANAGE',
  PERMISSION_MANAGE: 'PERMISSION_MANAGE',

  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  NOTIFICATIONS_VIEW: 'NOTIFICATIONS_VIEW',
  NOTIFICATIONS_MANAGE: 'NOTIFICATIONS_MANAGE',

  ATTENDANCE_VIEW_ALL: 'ATTENDANCE_VIEW_ALL',
  ATTENDANCE_VIEW_SELF: 'ATTENDANCE_VIEW_SELF',
  ATTENDANCE_CHECK_IN: 'ATTENDANCE_CHECK_IN',
  ATTENDANCE_CHECK_OUT: 'ATTENDANCE_CHECK_OUT',
  ATTENDANCE_APPROVE_REMOTE: 'ATTENDANCE_APPROVE_REMOTE',
  ATTENDANCE_EXPORT: 'ATTENDANCE_EXPORT',

  EVENTS_VIEW_UPCOMING: 'EVENTS_VIEW_UPCOMING',
  EVENTS_VIEW_PAST: 'EVENTS_VIEW_PAST',
  EVENTS_MANAGE_UPDATES: 'EVENTS_MANAGE_UPDATES',
  EVENTS_SUBMIT_REPORTS: 'EVENTS_SUBMIT_REPORTS',
  EVENTS_EXPORT_SUMMARY: 'EVENTS_EXPORT_SUMMARY',

  MEETINGS_VIEW_UPCOMING: 'MEETINGS_VIEW_UPCOMING',
  MEETINGS_VIEW_PAST: 'MEETINGS_VIEW_PAST',
  MEETINGS_MANAGE: 'MEETINGS_MANAGE',
  MEETINGS_EXPORT_SUMMARY: 'MEETINGS_EXPORT_SUMMARY',

  TODO_VIEW: 'TODO_VIEW',
  TODO_ASSIGN: 'TODO_ASSIGN',
  TODO_UPDATE_STATUS: 'TODO_UPDATE_STATUS',

  JOBS_VIEW_RECENT: 'JOBS_VIEW_RECENT',
  JOBS_MANAGE: 'JOBS_MANAGE',

  TRANSPORTATION_VIEW_ACTIVITY: 'TRANSPORTATION_VIEW_ACTIVITY',
  TRANSPORTATION_BOOK: 'TRANSPORTATION_BOOK',
  TRANSPORTATION_MANAGE: 'TRANSPORTATION_MANAGE',
  TRANSPORTATION_EXPORT: 'TRANSPORTATION_EXPORT'
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
