import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconClock,
  IconCalendarEvent,
  IconUsers,
  IconClipboardList,
  IconTruck,
  IconDots,
  IconCheckbox,
  IconClockCheck,
  IconHistory,
  IconReport,
  IconList,
  IconBook,
  IconMapPin,
  IconBell,
  IconCalendarStar,
  IconCalendarOff
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  attendance: IconClock,
  events: IconCalendarEvent,
  meeting: IconUsers,
  todo: IconClipboardList,
  transportation: IconTruck,
  more: IconDots,
  checkIn: IconCheckbox,
  checkOut: IconClockCheck,
  history: IconHistory,
  upcoming: IconCalendarEvent,
  past: IconHistory,
  updates: IconBell,
  reports: IconReport,
  summary: IconList,
  booking: IconBook,
  entry: IconMapPin,
  holidays: IconCalendarStar,
  leaves: IconCalendarOff
};
